# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
#/control/verbose 2
#
#/run/verbose 2
#/event/verbose 2
#/tracking/verbose 2
# 
# gamma 6 MeV to the direction (0.,0.,1.)
#
#/gun/particle gamma
#/gun/energy 6 MeV
#
#/run/beamOn 5
# 
# proton 210 MeV to the direction (0.,0.,1.)
#
#/gun/particle proton
#/gun/energy 2.5 MeV
#/tracking/verbose 2

#10M-12 min
/run/initialize
/run/beamOn 10000000
