/run/initialize
# for 241Am, using a different time threshold because daughter nucleaus is unstanle with t1/2 aroudn 1e5 years. 
/process/had/rdm/thresholdForVeryLongDecayTime 1e4 year
/gps/particle ion
/gps/energy 0 keV
/gps/ion 95 241 0 0   # Z=95 (Am), A=241, Q=0, E=0
/gps/number 1
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/radius 0.47 cm
/gps/pos/halfz 0.0005 cm
/gps/pos/centre 0 0 -4.43071 cm
/gps/pos/confine SourceCal
/run/beamOn 1000000 