/run/initialize
/gps/particle e-
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/radius 0.40 cm
/gps/pos/halfz 0.0005 cm
/gps/pos/centre 0 0 -4.43071 cm
/gps/pos/confine SourceCal
/gps/ang/type iso          # Isotropic emission
/gps/ene/type Mono         # Use Mono-energetic type
# /gps/ene/mono 976 keV      # Set the specific energy of the CE
# /run/beamOn 1000000
/gps/ene/mono 481.7 keV
/run/beamOn 1000000